/-
**Gluing width**: the arity of the cheapest scoped generating family for a
constraint, and its behaviour on the two running examples of the cohomology
paper (`papers/papers/ste-cohomology.tex`).

`Ste.SupportCover` proves `cechVanishesCover_iff_exists_scopedGeneration`:
the Čech obstruction of a cover `U` vanishes exactly when `T` is the
intersection of a scoped generating family whose scopes fit the cover
contexts.  Definition~\ref{def:gluingwidth} of the paper packages the least
context size for which this is possible as the **gluing width** `gw(T)`.
This file mechanizes it (`GluesAtWidth`) and Observation~\ref{obs:arity}'s
headline half-example: `allEqual n α` — the maximal coupling, whose
primal-graph treewidth is maximal (`n - 1`,
`Ste.CliqueTreewidth.treewidth_primalGraph_allEqualInstance`) — GLUES AT
has gluing width EXACTLY `1` for `n ≥ 2` and `|α| ≥ 2`: it is generated by
the pairwise-equality constraints, each of arity `2`
(`allEqual_gluesAtWidth_one`, `gw ≤ 1`), and it admits no width-`0` (i.e.
singleton-context) scoped generation
(`not_gluesAtWidth_zero_allEqual`, `gw ≥ 1`).  Both bounds are now
mechanized, so "exactly 1" IS claimed, under those two hypotheses (without
them the lower bound is false: a single variable, or a one-symbol
alphabet, makes `allEqual` a rectangle).

**Contents.**

* `pairEqConstraint i j`, `hasSupport_pairEqConstraint`: the two-variable
  equality constraint and its scope `{i, j}`.
* `pairCover n`, `pairCover_covers`: the cover of `Fin n` by all pairs.
* `allEqual_eq_iInter_pairEqConstraint`: `allEqual n α` is the intersection
  of the pairwise-equality constraints BY UNCURRYING ALONE (no transitivity
  argument): `∀ i j, f i = f j` is `∀ p, f p.1 = f p.2` after uncurrying.
* `cechVanishesCover_allEqual_pairCover`: hence, via
  `cechVanishesCover_of_refiningGenerators`, the Čech obstruction of the
  pair cover vanishes on `allEqual n α` — this is
  Proposition~\ref{prop:supportcover}(a) instantiated at the example that
  motivates Definition~\ref{def:gluingwidth}.
* `GluesAtWidth T w`: `T` admits a cover of contexts of size `≤ w + 1` over
  which the Čech obstruction vanishes — Definition~\ref{def:gluingwidth}.
* `allEqual_gluesAtWidth_one`: `allEqual n α` glues at width `1`, i.e.
  `gw ≤ 1` — the arity half of Observation~\ref{obs:arity} ("gluing width
  is arity, not treewidth").  The other half — that `allEqual`'s primal
  graph has treewidth `n - 1` — IS now mechanized, in `Ste.CliqueTreewidth`
  (`le_treewidth_of_isClique` supplies the clique lower bound;
  `treewidth_primalGraph_allEqualInstance` gives the equality `n - 1`), so
  the arity-vs-treewidth separation holds on both sides for `n ≥ 3`.
* `gluesAtWidth_iff_exists_cover_eq_iInter_sectionCylinder`: `GluesAtWidth`
  restated in cylinder form, via
  `cechVanishesCover_iff_eq_iInter_sectionCylinder`.
* `exists_eq_pi_of_gluesAtWidth_zero`: gluing at width `0` forces a
  nonempty constraint to be a rectangle (singleton-scoped generation plus
  `Ste.VariablePresheaf.singletonGlue_eq_pi`).
* `not_gluesAtWidth_zero_allEqual`: hence, with
  `Ste.CouplingLowerBound.allEqual_not_rectangular`, the gluing-width
  LOWER bound `gw(allEqual n α) ≥ 1` for `n ≥ 2`, `|α| ≥ 2` — the last
  piece of Observation~\ref{obs:arity}, previously unmechanized.

**Tier-3 punchline.**  `properColoring`, `edgeNeqConstraint`,
`cechVanishesCover_properColoring_edgeCover`: graph colourability is
generated by edge-scoped disequality constraints, so — by the same
`cechVanishesCover_of_refiningGenerators` pattern, disequality in place of
equality — it Čech-vanishes over the edge cover.  This mechanizes the
gluing-vanishing half of Observation~\ref{obs:arity}'s "more brutally"
example — under the hypothesis that `G` has NO ISOLATED VERTEX, without
which the edge cover fails to cover `W` and the statement does not apply.
Deciding `T ≠ ∅` (i.e. `k`-colourability itself) is NP-hard for
`k ≥ 3` (Karp 1972, "Reducibility Among Combinatorial Problems") — that
computational-hardness fact is NOT mechanized and is not in Mathlib; it is
cited here exactly as the memo cites it, as the point of the observation:
vanishing of the gluing obstruction over the natural cover is compatible
with full computational hardness, because all the hardness lives in
computing the genuine local sections the proposition quantifies over, not
in gluing them.
-/
import Ste.SupportCover
import Ste.CouplingLowerBound
import Mathlib.Combinatorics.SimpleGraph.Basic

namespace STE

open Set

/-! ### C1 — `allEqual` glues over the pair cover (gluing width 1) -/

variable {n : ℕ} {α : Type*}

/-- The **pairwise-equality constraint** on coordinates `i` and `j`: the
two-variable building block that generates `allEqual`. -/
def pairEqConstraint (i j : Fin n) : Set (Fin n → α) :=
  {f | f i = f j}

/-- `pairEqConstraint i j` is supported on `{i, j}`: it reads only those
two coordinates. -/
theorem hasSupport_pairEqConstraint (i j : Fin n) :
    HasSupport (A := fun _ : Fin n => α) (pairEqConstraint i j) ({i, j} : Set (Fin n)) := by
  intro f g hfg
  have hi : f i = g i := hfg i (Set.mem_insert _ _)
  have hj : f j = g j := hfg j (Set.mem_insert_of_mem _ rfl)
  show f i = f j ↔ g i = g j
  rw [hi, hj]

/-- The **pair cover** of `Fin n`: one context `{p.1, p.2}` for every
ordered pair of coordinates. -/
def pairCover (n : ℕ) : Fin n × Fin n → Set (Fin n) := fun p => {p.1, p.2}

/-- The pair cover covers every coordinate — take the diagonal pair
`(v, v)`. -/
theorem pairCover_covers : ∀ v : Fin n, ∃ p : Fin n × Fin n, v ∈ pairCover n p :=
  fun v => ⟨(v, v), Set.mem_insert _ _⟩

/-- **`allEqual` is the intersection of the pairwise equalities, by
uncurrying alone.**  Unfolding both sides, `∀ i j, f i = f j` becomes
`∀ p, f p.1 = f p.2` — no transitivity argument is involved, only
uncurrying. -/
theorem allEqual_eq_iInter_pairEqConstraint :
    (allEqual n α : Set (Fin n → α))
      = ⋂ p : Fin n × Fin n, pairEqConstraint p.1 p.2 := by
  ext f
  simp only [allEqual, Set.mem_setOf_eq, Set.mem_iInter, pairEqConstraint]
  exact ⟨fun h p => h p.1 p.2, fun h i j => h (i, j)⟩

/-- **C1 — `allEqual` glues over the pair cover.**  Combining the previous
three facts through `cechVanishesCover_of_refiningGenerators`: the Čech
obstruction of the pair cover vanishes on `allEqual n α`.  Mechanizes the
`allEqual` instance of Proposition~\ref{prop:supportcover}(a) that
Definition~\ref{def:gluingwidth} and Observation~\ref{obs:arity} build on. -/
theorem cechVanishesCover_allEqual_pairCover :
    CechVanishesCover (A := fun _ : Fin n => α) (allEqual n α) (pairCover n) :=
  cechVanishesCover_of_refiningGenerators (fun p => pairEqConstraint p.1 p.2)
    (pairCover n) (fun p => hasSupport_pairEqConstraint p.1 p.2)
    allEqual_eq_iInter_pairEqConstraint pairCover_covers
    (fun p => ⟨p, subset_rfl⟩)

/-! ### C2 — gluing width -/

/-- **Gluing width** (Definition~\ref{def:gluingwidth}): `T` *glues at
width `w`* if some cover of contexts, each of at most `w + 1` variables,
has vanishing Čech obstruction.  By
`cechVanishesCover_iff_exists_scopedGeneration` (`Ste.SupportCover`) this
is exactly the memo's "`gw(T)` is (one less than) the minimal arity of a
generating constraint family for `T`", read as an upper-bound predicate at
each `w`. -/
def GluesAtWidth {V : Type*} {A : V → Type*} (T : Set (∀ v, A v)) (w : ℕ) : Prop :=
  ∃ (ι : Type) (U : ι → Set V), (∀ v, ∃ j, v ∈ U j) ∧
    (∀ j, (U j).Finite ∧ (U j).ncard ≤ w + 1) ∧ CechVanishesCover T U

/-- Every context of the pair cover has at most `2` elements
(`Set.ncard_insert_le`, `Set.ncard_singleton`). -/
theorem pairCover_ncard_le (p : Fin n × Fin n) : (pairCover n p).ncard ≤ 2 := by
  show ({p.1, p.2} : Set (Fin n)).ncard ≤ 2
  calc ({p.1, p.2} : Set (Fin n)).ncard
      ≤ ({p.2} : Set (Fin n)).ncard + 1 := Set.ncard_insert_le _ _
    _ = 2 := by rw [Set.ncard_singleton]

/-- **`allEqual` glues at width `1`** — the `gw = 1` half of
Observation~\ref{obs:arity}: `allEqual n α` is generated by scope-`2`
pairwise-equality constraints (the pair cover), witnessed concretely by
`cechVanishesCover_allEqual_pairCover`, and every context of the pair
cover has at most `2 = 1 + 1` elements (`pairCover_ncard_le`). -/
theorem allEqual_gluesAtWidth_one :
    GluesAtWidth (A := fun _ : Fin n => α) (allEqual n α) 1 :=
  ⟨Fin n × Fin n, pairCover n, pairCover_covers,
    fun p => ⟨Set.toFinite _, pairCover_ncard_le p⟩,
    cechVanishesCover_allEqual_pairCover⟩

/-- **Gluing width, cylinder form** (restatement of
`cechVanishesCover_iff_eq_iInter_sectionCylinder` at the level of
`GluesAtWidth`).  `T` glues at width `w` exactly when some cover by
contexts of at most `w + 1` variables presents `T` as the intersection of
its own section cylinders.  No new machinery: the Čech condition in the
definition of `GluesAtWidth` is replaced verbatim by the cylinder
equation. -/
theorem gluesAtWidth_iff_exists_cover_eq_iInter_sectionCylinder
    {V : Type*} {A : V → Type*} (T : Set (∀ v, A v)) (w : ℕ) :
    GluesAtWidth T w ↔
      ∃ (ι : Type) (U : ι → Set V), (∀ v, ∃ j, v ∈ U j) ∧
        (∀ j, (U j).Finite ∧ (U j).ncard ≤ w + 1) ∧
        T = ⋂ j, sectionCylinder T U j := by
  constructor
  · rintro ⟨ι, U, hcover, hsize, hcech⟩
    exact ⟨ι, U, hcover, hsize,
      (cechVanishesCover_iff_eq_iInter_sectionCylinder hcover).mp hcech⟩
  · rintro ⟨ι, U, hcover, hsize, hEq⟩
    exact ⟨ι, U, hcover, hsize,
      (cechVanishesCover_iff_eq_iInter_sectionCylinder hcover).mpr hEq⟩

/-! ### C3 — the width-`0` lower bound -/

/-- **Width-`0` gluing forces rectangularity.**  A cover whose contexts
have at most one variable turns
`cechVanishesCover_iff_exists_scopedGeneration` into a *singleton*-scoped
generating family, and a nonempty constraint cut out by singleton-scoped
pieces is exactly the product of its coordinate projections
(`singletonGlue_eq_pi`, `Ste.VariablePresheaf`).  So gluing width `0` is
the same thing as being a rectangle. -/
theorem exists_eq_pi_of_gluesAtWidth_zero {V : Type*} {A : V → Type*}
    {T : Set (∀ v, A v)} (hT : T.Nonempty) (h : GluesAtWidth T 0) :
    ∃ P : ∀ v, Set (A v), T = Set.univ.pi P := by
  obtain ⟨ι, U, hcover, hsize, hcech⟩ := h
  obtain ⟨S, hsupp, hgen⟩ :=
    (cechVanishesCover_iff_exists_scopedGeneration hcover).mp hcech
  refine ⟨fun v => (fun f => f v) '' T, ?_⟩
  rw [← singletonGlue_eq_pi]
  refine Set.Subset.antisymm (subset_singletonGlue T) ?_
  intro f hf
  rw [hgen, Set.mem_iInter]
  intro j
  -- each context holds at most one variable
  have hsub : ∀ u ∈ U j, ∀ v ∈ U j, u = v := by
    intro u hu v hv
    by_contra hne
    have hss : ({u, v} : Set V) ⊆ U j := by
      intro x hx
      rcases Set.mem_insert_iff.mp hx with rfl | hx'
      · exact hu
      · rw [Set.mem_singleton_iff.mp hx']; exact hv
    have hle := Set.ncard_le_ncard hss (hsize j).1
    rw [Set.ncard_pair hne] at hle
    have := (hsize j).2
    omega
  rcases Set.eq_empty_or_nonempty (U j) with hUj | ⟨v, hv⟩
  · -- empty context: `S j` is trivial, and `T ⊆ S j` is nonempty, so `S j = univ`
    obtain ⟨g, hg⟩ := hT
    have hgS : g ∈ S j := by rw [hgen] at hg; exact Set.mem_iInter.mp hg j
    refine (hsupp j g f ?_).mp hgS
    intro u hu
    rw [hUj] at hu
    exact hu.elim
  · -- singleton context `{v}`: the projection witness at `v` already lies in `S j`
    obtain ⟨g, hg, hgf⟩ := mem_localSections.mp (mem_singletonGlue.mp hf v)
    have hgv : g v = f v := congrFun hgf ⟨v, rfl⟩
    have hgS : g ∈ S j := by rw [hgen] at hg; exact Set.mem_iInter.mp hg j
    refine (hsupp j g f ?_).mp hgS
    intro u hu
    rw [hsub u hu v hv]
    exact hgv

/-- **The gluing-width lower bound for the coupling** (`gw ≥ 1`).  For
`n ≥ 2` and at least two symbols, `allEqual n α` does NOT glue at width
`0`: a width-`0` cover would exhibit it as a rectangle
(`exists_eq_pi_of_gluesAtWidth_zero`), contradicting
`allEqual_not_rectangular` (`Ste.CouplingLowerBound`).  Together with
`allEqual_gluesAtWidth_one` this pins the gluing width of the maximal
coupling at exactly `1`, while its primal treewidth is `n - 1`
(`Ste.CliqueTreewidth.treewidth_primalGraph_allEqualInstance`):
Observation~\ref{obs:arity}, both sides. -/
theorem not_gluesAtWidth_zero_allEqual [Fintype α] (hn : 2 ≤ n)
    (hα : 2 ≤ Fintype.card α) :
    ¬ GluesAtWidth (A := fun _ : Fin n => α) (allEqual n α) 0 := by
  intro h
  have hne : Nonempty α := Fintype.card_pos_iff.mp (by omega)
  obtain ⟨a⟩ := hne
  have hT : (allEqual n α).Nonempty := ⟨fun _ => a, fun _ _ => rfl⟩
  exact allEqual_not_rectangular hn hα (exists_eq_pi_of_gluesAtWidth_zero hT h)

/-! ### Tier 3 — colourability Čech-vanishes over the edge cover -/

variable {W : Type*}

/-- **Colourability as a constraint.**  The proper `k`-colourings of a
graph `G`: assignments where no edge is monochromatic. Instantiates the
memo's "graph 3-colorability" at general `k` (`k = 3` recovers it). -/
def properColoring (G : SimpleGraph W) (k : ℕ) : Set (W → Fin k) :=
  {f | ∀ u v, G.Adj u v → f u ≠ f v}

/-- The **edge-scoped disequality constraint**: the two endpoints of an
edge must differ. -/
def edgeNeqConstraint (u v : W) (k : ℕ) : Set (W → Fin k) :=
  {f | f u ≠ f v}

/-- `edgeNeqConstraint u v k` is supported on `{u, v}`. -/
theorem hasSupport_edgeNeqConstraint (u v : W) (k : ℕ) :
    HasSupport (A := fun _ : W => Fin k) (edgeNeqConstraint u v k) ({u, v} : Set W) := by
  intro f g hfg
  have hu : f u = g u := hfg u (Set.mem_insert _ _)
  have hv : f v = g v := hfg v (Set.mem_insert_of_mem _ rfl)
  show f u ≠ f v ↔ g u ≠ g v
  rw [hu, hv]

/-- **Colourability is generated by edge-scoped disequalities.**
`properColoring G k` is, by uncurrying alone over `Sym2`-free adjacent
pairs (no further argument), the intersection of the per-edge disequality
constraints. -/
theorem properColoring_eq_iInter (G : SimpleGraph W) (k : ℕ) :
    properColoring G k
      = ⋂ p : {p : W × W // G.Adj p.1 p.2}, edgeNeqConstraint p.1.1 p.1.2 k := by
  ext f
  simp only [properColoring, Set.mem_setOf_eq, Set.mem_iInter, edgeNeqConstraint,
    Subtype.forall]
  constructor
  · intro h p hp
    exact h p.1 p.2 hp
  · intro h u v huv
    exact h (u, v) huv

/-- The **edge cover**: one context `{u, v}` for every adjacent pair. -/
def edgeCover (G : SimpleGraph W) : {p : W × W // G.Adj p.1 p.2} → Set W :=
  fun p => {p.1.1, p.1.2}

/-- **The Tier-3 punchline.**  If `G` has no isolated vertex (every
vertex has at least one neighbour, so the edge cover actually covers
`W`), the Čech obstruction of the edge cover vanishes on
`properColoring G k` — the same `cechVanishesCover_of_refiningGenerators`
pattern as `cechVanishesCover_allEqual_pairCover`, disequality in place of
equality.  This mechanizes the gluing-vanishing half of
Observation~\ref{obs:arity}'s "more brutally" example: gluing is free even
though deciding `properColoring G k ≠ ∅` (`k`-colourability) is NP-hard
for `k ≥ 3` (Karp 1972) — an external fact, not mechanized, not in
Mathlib, and not claimed here. -/
theorem cechVanishesCover_properColoring_edgeCover (G : SimpleGraph W) (k : ℕ)
    (hcover : ∀ v, ∃ w, G.Adj v w) :
    CechVanishesCover (A := fun _ : W => Fin k) (properColoring G k) (edgeCover G) :=
  cechVanishesCover_of_refiningGenerators
    (fun p => edgeNeqConstraint p.1.1 p.1.2 k) (edgeCover G)
    (fun p => hasSupport_edgeNeqConstraint p.1.1 p.1.2 k)
    (properColoring_eq_iInter G k)
    (fun v => let ⟨w, hw⟩ := hcover v; ⟨⟨(v, w), hw⟩, Set.mem_insert _ _⟩)
    (fun p => ⟨p, subset_rfl⟩)

end STE
