/-
**Gluing width**: the arity of the cheapest scoped generating family for a
constraint, and its behaviour on the two running examples of the cohomology
exploration memo (`papers/notes/ste-cohomology-exploration.tex`).

`Ste.SupportCover` proves `cechVanishesCover_iff_exists_scopedGeneration`:
the Čech obstruction of a cover `U` vanishes exactly when `T` is the
intersection of a scoped generating family whose scopes fit the cover
contexts.  Definition~\ref{def:gluingwidth} of the memo packages the least
context size for which this is possible as the **gluing width** `gw(T)`; it
was stated there as "not mechanized".  This file mechanizes it
(`GluesAtWidth`) and Observation~\ref{obs:arity}'s headline half-example:
`allEqual n α` — the maximal coupling, whose (primal-graph) induced width is
maximal (`n - 1`, prose observation in `Ste.CouplingLowerBound`) — has
gluing width exactly `1`: it is generated by the pairwise-equality
constraints, each of arity `2`.

**Contents.**

* `pairEqConstraint i j`, `hasSupport_pairEqConstraint`: the two-variable
  equality constraint and its scope `{i, j}`.
* `pairCover n`, `pairCover_covers`: the cover of `Fin n` by all pairs.
* `allEqual_eq_iInter_pairEqConstraint`: `allEqual n α` is *definitionally*
  the intersection of the pairwise-equality constraints — no transitivity
  chasing needed, `∀ i j, f i = f j` unfolds to exactly that intersection.
* `cechVanishesCover_allEqual_pairCover`: hence, via
  `cechVanishesCover_of_refiningGenerators`, the Čech obstruction of the
  pair cover vanishes on `allEqual n α` — this is
  Proposition~\ref{prop:supportcover}(a) instantiated at the example that
  motivates Definition~\ref{def:gluingwidth}.
* `GluesAtWidth T w`: `T` admits a cover of contexts of size `≤ w + 1` over
  which the Čech obstruction vanishes — Definition~\ref{def:gluingwidth}.
* `allEqual_gluesAtWidth_one`: `allEqual n α` glues at width `1` — the
  `gw = 1` half of Observation~\ref{obs:arity} ("gluing width is arity, not
  treewidth").  The other half of the observation — that the *induced
  width* of `allEqual`'s primal graph is `n - 1` — stays the prose
  observation it already is in `Ste.CouplingLowerBound`; formalizing it
  would need a treewidth *lower bound* from clique size that the repository
  does not yet have (`Ste.GraphTreewidth` proves only the upper bound
  `treewidth_le_card`), so it is deliberately left unmechanized here rather
  than faked.

**Tier-3 punchline.**  `properColoring`, `edgeNeqConstraint`,
`cechVanishesCover_properColoring_edgeCover`: graph (list-)colourability is
generated by edge-scoped disequality constraints, so — by the same
`cechVanishesCover_of_refiningGenerators` pattern, disequality in place of
equality — it Čech-vanishes over the edge cover.  This mechanizes the
`Ȟ⁰`-vanishing half of Observation~\ref{obs:arity}'s "more brutally"
example.  Deciding `T ≠ ∅` (i.e. `k`-colourability itself) is NP-hard for
`k ≥ 3` (Karp 1972, "Reducibility Among Combinatorial Problems") — that
computational-hardness fact is NOT mechanized and is not in Mathlib; it is
cited here exactly as the memo cites it, as the point of the observation:
vanishing of the gluing obstruction over the natural cover is compatible
with full computational hardness, because all the hardness lives in
computing the genuine local sections the proposition quantifies over, not
in gluing them.
-/
import Ste.SupportCover
import Ste.CouplingLowerBound
import Mathlib.Combinatorics.SimpleGraph.Basic

namespace STE

open Set

/-! ### C1 — `allEqual` glues over the pair cover (gluing width 1) -/

variable {n : ℕ} {α : Type*}

/-- The **pairwise-equality constraint** on coordinates `i` and `j`: the
two-variable building block that generates `allEqual`. -/
def pairEqConstraint (i j : Fin n) : Set (Fin n → α) :=
  {f | f i = f j}

/-- `pairEqConstraint i j` is supported on `{i, j}`: it reads only those
two coordinates. -/
theorem hasSupport_pairEqConstraint (i j : Fin n) :
    HasSupport (A := fun _ : Fin n => α) (pairEqConstraint i j) ({i, j} : Set (Fin n)) := by
  intro f g hfg
  have hi : f i = g i := hfg i (Set.mem_insert _ _)
  have hj : f j = g j := hfg j (Set.mem_insert_of_mem _ rfl)
  show f i = f j ↔ g i = g j
  rw [hi, hj]

/-- The **pair cover** of `Fin n`: one context `{p.1, p.2}` for every
ordered pair of coordinates. -/
def pairCover (n : ℕ) : Fin n × Fin n → Set (Fin n) := fun p => {p.1, p.2}

/-- The pair cover covers every coordinate — take the diagonal pair
`(v, v)`. -/
theorem pairCover_covers : ∀ v : Fin n, ∃ p : Fin n × Fin n, v ∈ pairCover n p :=
  fun v => ⟨(v, v), Set.mem_insert _ _⟩

/-- **`allEqual` is (definitionally) the intersection of the pairwise
equalities.**  Unfolding both sides, `∀ i j, f i = f j` *is* `∀ p, f p.1 =
f p.2` — no transitivity chasing, just uncurrying. -/
theorem allEqual_eq_iInter_pairEqConstraint :
    (allEqual n α : Set (Fin n → α))
      = ⋂ p : Fin n × Fin n, pairEqConstraint p.1 p.2 := by
  ext f
  simp only [allEqual, Set.mem_setOf_eq, Set.mem_iInter, pairEqConstraint]
  exact ⟨fun h p => h p.1 p.2, fun h i j => h (i, j)⟩

/-- **C1 — `allEqual` glues over the pair cover.**  Combining the previous
three facts through `cechVanishesCover_of_refiningGenerators`: the Čech
obstruction of the pair cover vanishes on `allEqual n α`.  Mechanizes the
`allEqual` instance of Proposition~\ref{prop:supportcover}(a) that
Definition~\ref{def:gluingwidth} and Observation~\ref{obs:arity} build on. -/
theorem cechVanishesCover_allEqual_pairCover :
    CechVanishesCover (A := fun _ : Fin n => α) (allEqual n α) (pairCover n) :=
  cechVanishesCover_of_refiningGenerators (fun p => pairEqConstraint p.1 p.2)
    (pairCover n) (fun p => hasSupport_pairEqConstraint p.1 p.2)
    allEqual_eq_iInter_pairEqConstraint pairCover_covers
    (fun p => ⟨p, subset_rfl⟩)

/-! ### C2 — gluing width -/

/-- **Gluing width** (Definition~\ref{def:gluingwidth}): `T` *glues at
width `w`* if some cover of contexts, each of at most `w + 1` variables,
has vanishing Čech obstruction.  By
`cechVanishesCover_iff_exists_scopedGeneration` (`Ste.SupportCover`) this
is exactly the memo's "`gw(T)` is (one less than) the minimal arity of a
generating constraint family for `T`", read as an upper-bound predicate at
each `w`. -/
def GluesAtWidth {V : Type*} {A : V → Type*} (T : Set (∀ v, A v)) (w : ℕ) : Prop :=
  ∃ (ι : Type) (U : ι → Set V), (∀ v, ∃ j, v ∈ U j) ∧
    (∀ j, (U j).Finite ∧ (U j).ncard ≤ w + 1) ∧ CechVanishesCover T U

/-- Every context of the pair cover has at most `2` elements
(`Set.ncard_insert_le`, `Set.ncard_singleton`). -/
theorem pairCover_ncard_le (p : Fin n × Fin n) : (pairCover n p).ncard ≤ 2 := by
  show ({p.1, p.2} : Set (Fin n)).ncard ≤ 2
  calc ({p.1, p.2} : Set (Fin n)).ncard
      ≤ ({p.2} : Set (Fin n)).ncard + 1 := Set.ncard_insert_le _ _
    _ = 2 := by rw [Set.ncard_singleton]

/-- **`allEqual` glues at width `1`** — the `gw = 1` half of
Observation~\ref{obs:arity}: `allEqual n α` is generated by scope-`2`
pairwise-equality constraints (the pair cover), witnessed concretely by
`cechVanishesCover_allEqual_pairCover`, and every context of the pair
cover has at most `2 = 1 + 1` elements (`pairCover_ncard_le`). -/
theorem allEqual_gluesAtWidth_one :
    GluesAtWidth (A := fun _ : Fin n => α) (allEqual n α) 1 :=
  ⟨Fin n × Fin n, pairCover n, pairCover_covers,
    fun p => ⟨Set.toFinite _, pairCover_ncard_le p⟩,
    cechVanishesCover_allEqual_pairCover⟩

/-! ### Tier 3 — colourability Čech-vanishes over the edge cover -/

variable {W : Type*}

/-- **Colourability as a constraint.**  The proper `k`-colourings of a
graph `G`: assignments where no edge is monochromatic. Instantiates the
memo's "graph 3-colorability" at general `k` (`k = 3` recovers it). -/
def properColoring (G : SimpleGraph W) (k : ℕ) : Set (W → Fin k) :=
  {f | ∀ u v, G.Adj u v → f u ≠ f v}

/-- The **edge-scoped disequality constraint**: the two endpoints of an
edge must differ. -/
def edgeNeqConstraint (u v : W) (k : ℕ) : Set (W → Fin k) :=
  {f | f u ≠ f v}

/-- `edgeNeqConstraint u v k` is supported on `{u, v}`. -/
theorem hasSupport_edgeNeqConstraint (u v : W) (k : ℕ) :
    HasSupport (A := fun _ : W => Fin k) (edgeNeqConstraint u v k) ({u, v} : Set W) := by
  intro f g hfg
  have hu : f u = g u := hfg u (Set.mem_insert _ _)
  have hv : f v = g v := hfg v (Set.mem_insert_of_mem _ rfl)
  show f u ≠ f v ↔ g u ≠ g v
  rw [hu, hv]

/-- **Colourability is generated by edge-scoped disequalities.**
`properColoring G k` is (definitionally, up to uncurrying `Sym2`-free
adjacent pairs) the intersection of the per-edge disequality
constraints. -/
theorem properColoring_eq_iInter (G : SimpleGraph W) (k : ℕ) :
    properColoring G k
      = ⋂ p : {p : W × W // G.Adj p.1 p.2}, edgeNeqConstraint p.1.1 p.1.2 k := by
  ext f
  simp only [properColoring, Set.mem_setOf_eq, Set.mem_iInter, edgeNeqConstraint,
    Subtype.forall]
  constructor
  · intro h p hp
    exact h p.1 p.2 hp
  · intro h u v huv
    exact h (u, v) huv

/-- The **edge cover**: one context `{u, v}` for every adjacent pair. -/
def edgeCover (G : SimpleGraph W) : {p : W × W // G.Adj p.1 p.2} → Set W :=
  fun p => {p.1.1, p.1.2}

/-- **The Tier-3 punchline.**  If `G` has no isolated vertex (every
vertex has at least one neighbour, so the edge cover actually covers
`W`), the Čech obstruction of the edge cover vanishes on
`properColoring G k` — the same `cechVanishesCover_of_refiningGenerators`
pattern as `cechVanishesCover_allEqual_pairCover`, disequality in place of
equality.  This mechanizes the `Ȟ⁰`-vanishing half of
Observation~\ref{obs:arity}'s "more brutally" example: gluing is free even
though deciding `properColoring G k ≠ ∅` (`k`-colourability) is NP-hard
for `k ≥ 3` (Karp 1972) — an external fact, not mechanized, not in
Mathlib, and not claimed here. -/
theorem cechVanishesCover_properColoring_edgeCover (G : SimpleGraph W) (k : ℕ)
    (hcover : ∀ v, ∃ w, G.Adj v w) :
    CechVanishesCover (A := fun _ : W => Fin k) (properColoring G k) (edgeCover G) :=
  cechVanishesCover_of_refiningGenerators
    (fun p => edgeNeqConstraint p.1.1 p.1.2 k) (edgeCover G)
    (fun p => hasSupport_edgeNeqConstraint p.1.1 p.1.2 k)
    (properColoring_eq_iInter G k)
    (fun v => let ⟨w, hw⟩ := hcover v; ⟨⟨(v, w), hw⟩, Set.mem_insert _ _⟩)
    (fun p => ⟨p, subset_rfl⟩)

end STE
