/-
**Support–cover gluing**: the Čech obstruction of a cover vanishes exactly
when the constraint is generated by constraints whose scopes fit inside the
cover contexts.

`Ste.CechCover` proves that *rectangular* constraints glue over every cover
(`rectangular_cechVanishesCover`) and that gluing at the singleton cover is
equivalent to rectangularity (`Ste.CouplingLowerBound.cechVanishes_iff_rectangular`).
This file closes the general gap between those two facts, over an arbitrary
cover `U : J → Set V`: the sheaf/gluing obstruction of `U` sees nothing but
the *scope* structure of the constraint.

For a cover `U`, the **section cylinder** of context `U j` is the constraint
`{f | (U j).restrict f ∈ localSections T (U j)}` — the pullback of `T`'s
genuine local sections over `U j`. Each cylinder has support `U j`
(`hasSupport_sectionCylinder`). The two directions:

* **(a) refining generators ⇒ vanishing** (`cechVanishesCover_of_refiningGenerators`):
  if `T = ⋂ i, S i` with each `HasSupport (S i) (σ i)` and every scope
  `σ i` contained in some context `U j`, then every compatible family of
  local sections glues. No acyclicity of the nerve is needed: STE local
  sections carry a global witness, and a scope-`σ i` constraint only reads
  coordinates inside one context, where the glue already matches that
  witness.
* **(b) vanishing ⇒ the cylinders generate** (the forward half of
  `cechVanishesCover_iff_eq_iInter_sectionCylinder`): if the obstruction
  vanishes then `T = ⋂ j, sectionCylinder T U j`, so `T` is the
  intersection of its own section cylinders, a scoped generating family.

Combined: `cechVanishesCover_iff_exists_scopedGeneration` —
`CechVanishesCover T U` iff `T` admits a per-context scoped generating
family. This mechanizes the "support–cover gluing" proposition of the
cohomology exploration note (`papers/notes/ste-cohomology-exploration.tex`),
which was stated there only as a conjecture-with-proof-sketch. The upshot:
the gluing layer of STE is governed entirely by whether the constraint's
generators fit the cover — all remaining difficulty lives in *computing the
local sections*, never in gluing them.
-/
import Ste.CechCover
import Ste.Support

namespace STE

open Set

variable {V : Type*} {A : V → Type*} {J : Type*}

/-- **The section cylinder** of context `U j`: the pullback of `T`'s local
sections over `U j`. It has support `U j`. -/
def sectionCylinder (T : Set (∀ v, A v)) (U : J → Set V) (j : J) :
    Set (∀ v, A v) :=
  {f | (U j).restrict f ∈ localSections T (U j)}

/-- The section cylinder over `U j` depends only on the coordinates in
`U j`. -/
theorem hasSupport_sectionCylinder (T : Set (∀ v, A v)) (U : J → Set V)
    (j : J) : HasSupport (sectionCylinder T U j) (U j) := by
  intro f g hfg
  have hres : (U j).restrict f = (U j).restrict g :=
    funext fun v => hfg v.1 v.2
  show (U j).restrict f ∈ localSections T (U j) ↔
       (U j).restrict g ∈ localSections T (U j)
  rw [hres]

/-- **(a) Refining generators force gluing.** If `T` is the intersection of
constraints whose scopes each fit inside some cover context, then the Čech
obstruction of the cover vanishes: every compatible family of local
sections glues to a global solution. -/
theorem cechVanishesCover_of_refiningGenerators
    {I : Type*} {T : Set (∀ v, A v)} (S : I → Set (∀ v, A v)) (σ : I → Set V)
    (hsupp : ∀ i, HasSupport (S i) (σ i)) (hgen : T = ⋂ i, S i)
    {U : J → Set V} (hcover : ∀ v, ∃ j, v ∈ U j)
    (hrefine : ∀ i, ∃ j, σ i ⊆ U j) :
    CechVanishesCover T U := by
  rintro s ⟨hsec, hcompat⟩
  -- The glue: at each variable read the section from any chosen context.
  refine ⟨fun v => s (hcover v).choose ⟨v, (hcover v).choose_spec⟩, ?_, ?_⟩
  · -- membership: the glue lies in every generator `S i`
    rw [hgen, Set.mem_iInter]
    intro i
    obtain ⟨j0, hj0⟩ := hrefine i
    obtain ⟨g, hg, hgs⟩ := hsec j0          -- g ∈ T, (U j0).restrict g = s j0
    have hgSi : g ∈ S i := by rw [hgen] at hg; exact Set.mem_iInter.mp hg i
    -- the glue agrees with the witness g on the scope σ i ⊆ U j0
    refine (hsupp i _ g ?_).mpr hgSi
    intro v hv
    have hvUj0 : v ∈ U j0 := hj0 hv
    have e1 : s (hcover v).choose ⟨v, (hcover v).choose_spec⟩ = s j0 ⟨v, hvUj0⟩ :=
      hcompat (hcover v).choose j0 v (hcover v).choose_spec hvUj0
    have e2 : s j0 ⟨v, hvUj0⟩ = g v := (congrFun hgs ⟨v, hvUj0⟩).symm
    show s (hcover v).choose ⟨v, (hcover v).choose_spec⟩ = g v
    rw [e1, e2]
  · -- the glue restricts to the prescribed section on each context
    intro j
    funext u
    obtain ⟨u, hu⟩ := u
    show s (hcover u).choose ⟨u, (hcover u).choose_spec⟩ = s j ⟨u, hu⟩
    exact hcompat (hcover u).choose j u (hcover u).choose_spec hu

/-- **The cover-gluing iff, cylinder form.** The Čech obstruction of `U`
vanishes exactly when `T` equals the intersection of its own section
cylinders. -/
theorem cechVanishesCover_iff_eq_iInter_sectionCylinder
    {T : Set (∀ v, A v)} {U : J → Set V} (hcover : ∀ v, ∃ j, v ∈ U j) :
    CechVanishesCover T U ↔ T = ⋂ j, sectionCylinder T U j := by
  constructor
  · intro h
    apply Set.eq_of_subset_of_subset
    · -- T sits in every cylinder (restrict a global solution)
      intro f hf
      rw [Set.mem_iInter]
      exact fun j => restrict_mem_localSections (U j) hf
    · -- a point of every cylinder assembles a compatible family, which glues
      intro f hf
      rw [Set.mem_iInter] at hf
      have hcompat : CompatibleFamily T U (fun j => (U j).restrict f) :=
        ⟨fun j => hf j, fun _ _ _ _ _ => rfl⟩
      obtain ⟨g, hg, hgres⟩ := h _ hcompat
      have hgf : g = f := glueCover_unique hcover hgres (fun _ => rfl)
      rw [← hgf]; exact hg
  · intro hEq
    exact cechVanishesCover_of_refiningGenerators (sectionCylinder T U) U
      (fun j => hasSupport_sectionCylinder T U j) hEq hcover
      (fun j => ⟨j, subset_rfl⟩)

/-- **Support–cover gluing (packaged).** The Čech obstruction of the cover
`U` vanishes iff `T` admits a per-context *scoped generating family*: a
family `S : J → Set (∀ v, A v)` with `HasSupport (S j) (U j)` whose
intersection is `T`. Gluing over `U` is possible exactly when the
constraint is cut out by pieces that each read only one context. -/
theorem cechVanishesCover_iff_exists_scopedGeneration
    {T : Set (∀ v, A v)} {U : J → Set V} (hcover : ∀ v, ∃ j, v ∈ U j) :
    CechVanishesCover T U ↔
      ∃ S : J → Set (∀ v, A v),
        (∀ j, HasSupport (S j) (U j)) ∧ T = ⋂ j, S j := by
  constructor
  · intro h
    exact ⟨sectionCylinder T U, fun j => hasSupport_sectionCylinder T U j,
      (cechVanishesCover_iff_eq_iInter_sectionCylinder hcover).mp h⟩
  · rintro ⟨S, hsupp, hgen⟩
    exact cechVanishesCover_of_refiningGenerators S U hsupp hgen hcover
      (fun j => ⟨j, subset_rfl⟩)

end STE
